/**This class serves as unit test for the BatchServiceReportTracker class
***@Developer: Izay Ramos-Irizarry
***@Date:      7/1/2015
***@Version:   1.0
*/
@isTest(SeeAllData=true)
public class BatchServiceReportTracker_UT {
    public static TestMethod void test1(){
        BatchServiceReportTracker_Scheduler bs = new BatchServiceReportTracker_Scheduler();
        BatchServiceReportTracker b = new BatchServiceReportTracker();
    }
    
}